# Generated by Django 3.2.10 on 2022-05-02 08:11

import django.core.validators
from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emailAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=order.models.increment_order_number, max_length=100, unique=True)),
                ('subject', models.CharField(choices=[('Subject one', 'Subject one'), ('Subject two', 'Subject two'), ('Subject three', 'Subject three'), ('Subject four', 'Subject four')], default='Subject one', max_length=100)),
                ('prefered_format', models.CharField(blank=True, choices=[('PDF', 'PDF'), ('WORD(.docx)', 'WORD(.docx)'), ('APA', 'APA')], max_length=200, null=True)),
                ('number_of_sources', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_pages', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('powerpoint_slides', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('assignment_details', models.TextField(blank=True, max_length=100, null=True)),
                ('assignment_file', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('total_price', models.CharField(blank=True, max_length=100, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
