# Generated by Django 3.2.10 on 2022-05-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_made',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
